# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('base_currency', djmoney.models.fields.CurrencyField(default='XYZ', max_length=3)),
                ('exchange_rate', models.FloatField()),
            ],
        ),
    ]
